### PR TITLE
Open up Cursor datatype

### PR DESCRIPTION
**Pull request by jcristovao**
In order to allow for custom (less verbose) pretty printers of a cursor, could this datatype constructors be exported?
Thanks

### CODE REVIEW

**Comment by snoyberg** [comment]
Can you clarify what you're trying to do here? It seems like `node` should provide you what you need. I'm hesitant to open up this data type as it can allow users to break the abstraction of the library.

**Comment by jcristovao** [comment]
Yes, I know this is not recommendable and please fell free to close this: my use case is quite a simplification, print only some relevant fields ignoring most - ideally a Node to Hamlet for HTML would be optimum, but honestly I don't have time to that - and hamlet is html specific - thus not applicable to this (XML) package.

**Comment by snoyberg** [comment]
Does `toHtml . node` not do what you want?

**Comment by jcristovao** [comment]
Of course it does, nevermind. I don't know how I've missed ```node```.
Thanks, and sorry for the noise

**Comment by snoyberg** [comment]
No problem, glad I could help.

**Pull request closed without merging**
