### PR TITLE
Added lookahead combinators that allow conditional consumption of tags.

### PR DESCRIPTION
**Pull request by merijn**
When dealing with messier XML scraped from the web I occasionally don't know exactly which tags I need to accept, so I find it useful to write some catch-all combinators that output "unexpected" tags. Now, there is a `takeAllTreesContent`, but that consume *anything* and as a result makes a rather poor fallback in, for example, uses of `many`.

The newly added `lookahead` and friends allow me to conditionally consume an entire tree/tag. One example would be something like:

```

debugParser :: MonadThrow m => Name -> ConduitM Event o m ()
debugParser name = lookaheadPredicateIgnoreAttrs (not . (==name)) $ do
    t <- renderText def .| fold
   T.putStrLn t

parseAll = do
    manyYield $ choose [fooParser, barParser, debugParser "quux"]
    tagName "quux"  {- ... -}
```

Here `debugParser` consumes any tag that is not "quux" and plugs nicely into renderText from `Text.XML.Stream.Render` to display the offending tags.

### CODE REVIEW

**Comment by merijn** [comment]
Actually, this patch as-is is broken, since it depends on `takeAllTreesContent` working as described in the docs, which it doesn't, as mentioned in #98

**Comment by k0ral** [comment]
It makes sense, I don't think there's a way to do that with the existing parsers/combinators. I will just try and find a different name for the new functions, as `lookahead` wrongly suggests that nothing is consumed from the stream. I'll probably also rename `takeAllTreesContent` accordingly, since it clearly falls into the same category of parsers.

**Comment by k0ral** [comment]
After thinking about it, I intend to implement the following:

```haskell
-- Consume-and-yield events of a single tag tree, as long as it matches given name and attribute parsers
takeTreesContent :: MonadThrow m => NameMatcher a -> AttrParser b -> ConduitM Event Event m (Maybe ())

takeAllTreesContent = takeTreesContent anyName ignoreAttrs
```
(I've introduced `NameMatcher` in https://github.com/snoyberg/xml/commit/48e68c2bdf7ff39bc11e2f77c0aa55536a849440)

This should cover your use case, as follows:
```haskell
debugParser :: MonadThrow m => Name -> ConduitM Event o m ()
debugParser name = do
  t <- takeTreesContent (matching (/= name)) ignoreAttrs .| renderBytes def .| foldC
  if null t
  then return Nothing
  else putStrLn t >> return (Just ())

parseAll = do
    manyYield $ choose [fooParser, barParser, debugParser "quux"]
    tagName "quux"  {- ... -}
```
(I didn't typecheck it, but you get the idea)

If you're okay with that approach, I'll implement it and make a release out of everything you've contributed.

**Comment by merijn** [comment]
Yeah, that looks fine for my usecase(s).

**Comment by k0ral** [comment]
Implemented on release 1.5.0 (not yet on Hackage). Thank you !

**Comment by k0ral** [comment]
@merijn Release 1.5.0 is now available on Hackage, you can start working with it by setting it explicitly as a dependence of your project, otherwise a version <1.5 will be selected by default by cabal.
Please let me know if you experience any issue.

**Pull request closed without merging**
